// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/soso/Homepage.tsx": () => import("../components/mockups/soso/Homepage.tsx"),
  "./components/mockups/soso/ProductPage.tsx": () => import("../components/mockups/soso/ProductPage.tsx")
};
